version: "3.9"
services:
  llm-app-dev:
    container_name: "llm-app-dev"
    build:
      dockerfile: Dockerfile
      context: .
      network: host
    image: "llm-app-dev"
    stdin_open: true
    tty: true
    ports:
      - 81:80
    secrets:
      - openai_api_key
    volumes:
      - .:/workspaces
      # - /tmp/upload:/upload
    environment:
      - COLLECTION=dev
    command: streamlit run src/entrypoint/app.py --server.port 80

secrets:
  openai_api_key:
    file: ./secrets/openai_api_key.json
